/**
 * CursorAiService - интеграция с Cursor AI Pane
 * 
 * Поскольку Cursor не предоставляет публичного API для программной отправки сообщений в AI Pane,
 * используем clipboard + уведомления как наиболее удобный workaround.
 * 
 * В будущем, если Cursor добавит официальное API, можно будет легко заменить реализацию.
 */
import * as vscode from "vscode";
import { logInfo, logDebug } from "../logging/log";

export interface CursorAiOptions {
  /** Префикс для сообщения (например, указание что это от LG) */
  prefix?: string;
  /** Показывать ли детальное уведомление пользователю */
  showDetailedNotification?: boolean;
}

export class CursorAiService {
  
  /**
   * Отправляет контент в Cursor AI Pane через clipboard.
   * 
   * @param content - контент для отправки
   * @param options - дополнительные опции
   */
  static async sendToAI(content: string, options: CursorAiOptions = {}): Promise<void> {
    const { prefix, showDetailedNotification = true } = options;
    
    try {
      // Подготавливаем финальный контент
      let finalContent = content;
      if (prefix) {
        finalContent = `${prefix}\n\n${content}`;
      }
      
      // Копируем в clipboard
      await vscode.env.clipboard.writeText(finalContent);
      
      logInfo(`[CursorAI] Content copied to clipboard, length: ${finalContent.length} chars`);
      logDebug(`[CursorAI] Content preview: ${finalContent.slice(0, 200)}...`);
      
      if (showDetailedNotification) {
        // Показываем подробное уведомление с инструкциями
        const action = await vscode.window.showInformationMessage(
          `✅ LG content copied to clipboard (${this.formatSize(finalContent.length)})\n\n` +
          "📋 Next steps:\n" +
          "1. Open Cursor AI Pane (Ctrl+L or Cmd+L)\n" +
          "2. Paste content (Ctrl+V or Cmd+V)\n" +
          "3. Start your conversation!",
          { modal: false },
          "✨ Open Cursor AI",
          "📚 Got it"
        );
        
        if (action === "✨ Open Cursor AI") {
          // Пытаемся открыть Cursor AI через известные команды
          await this.tryOpenCursorAI();
        }
      } else {
        // Простое уведомление
        vscode.window.showInformationMessage(
          `📋 LG content copied! Paste it in Cursor AI (${this.formatSize(finalContent.length)})`
        );
      }
      
    } catch (error: any) {
      const message = `Failed to send content to Cursor AI: ${error?.message || error}`;
      logInfo(`[CursorAI] Error: ${message}`);
      vscode.window.showErrorMessage(message);
      throw error;
    }
  }
  
  /**
   * Отправляет сгенерированный контекст в Cursor AI
   */
  static async sendContext(templateName: string, content: string): Promise<void> {
    const prefix = `# 🎯 LG Context: ${templateName}\n\n` +
                  `Generated by Listing Generator from template \`${templateName}\`.\n` +
                  `This context was carefully prepared to fit within model limits.`;
    
    await this.sendToAI(content, { 
      prefix,
      showDetailedNotification: true 
    });
  }
  
  /**
   * Отправляет сгенерированный листинг в Cursor AI
   */
  static async sendListing(sectionName: string, mode: string, content: string): Promise<void> {
    const prefix = `# 📋 LG Listing: ${sectionName} (${mode})\n\n` +
                  `Generated by Listing Generator from section \`${sectionName}\` in \`${mode}\` mode.\n` +
                  `This listing includes only relevant files that passed the configured filters.`;
    
    await this.sendToAI(content, { 
      prefix,
      showDetailedNotification: true 
    });
  }
  
  /**
   * Попытка открыть Cursor AI Pane через известные команды
   */
  private static async tryOpenCursorAI(): Promise<void> {
    const possibleCommands = [
      'cursor.openAIPane',
      'cursor.showAIChat',
      'cursor.ai.open',
      'workbench.action.chat.open',
      // Если есть другие команды, можно добавить
    ];
    
    for (const command of possibleCommands) {
      try {
        await vscode.commands.executeCommand(command);
        logDebug(`[CursorAI] Successfully executed command: ${command}`);
        return;
      } catch (error) {
        logDebug(`[CursorAI] Command ${command} failed: ${error}`);
        // Продолжаем пробовать следующие команды
      }
    }
    
    // Если ни одна команда не сработала, показываем инструкцию
    vscode.window.showInformationMessage(
      "Please manually open Cursor AI Pane (Ctrl+L or Cmd+L) and paste the content."
    );
  }
  
  /**
   * Форматирует размер контента для отображения пользователю
   */
  private static formatSize(length: number): string {
    if (length < 1000) {
      return `${length} chars`;
    } else if (length < 1000000) {
      return `${(length / 1000).toFixed(1)}K chars`;
    } else {
      return `${(length / 1000000).toFixed(1)}M chars`;
    }
  }
}
