/**
 * Generator for ai-interaction.sec.yaml template file.
 *
 * Collects supported modes from all registered AI providers
 * and generates/updates the canonical integration meta-section.
 */
import * as fs from "fs";
import * as path from "path";
import { Document, parseDocument, YAMLMap, YAMLSeq, Pair, isMap } from "yaml";
import { AiIntegrationService } from "./AiIntegrationService";
import { effectiveWorkspaceRoot } from "../cli/CliResolver";
import { logInfo, logDebug } from "../logging/log";

/**
 * Mode metadata (without runs).
 */
interface ModeMeta {
  title: string;
  description?: string;
  tags?: string[];
}

/**
 * Parsed mode data from existing file.
 * Includes metadata and preserves provider order.
 */
interface ParsedModeData {
  meta: ModeMeta;
  /** Providers in original order from file */
  providerOrder: string[];
  runs: Map<string, string>;
}

/**
 * Canonical mode definitions with metadata.
 */
const CANONICAL_MODES: Record<string, ModeMeta> = {
  ask: {
    title: "Ask",
    description: "Question-answer mode"
  },
  agent: {
    title: "Agent",
    description: "Agent mode with tools",
    tags: ["agent"]
  },
  plan: {
    title: "Plan",
    description: "Planning / specification mode",
    tags: ["agent", "plan"]
  }
};

/**
 * Header comment for generated file.
 */
const FILE_HEADER_COMMENT =
  " Auto-generated by Listing Generator IDE plugins\n" +
  " This file defines AI provider integration modes.\n" +
  " Manual edits to unknown providers/modes will be preserved.";

/**
 * Generates and updates ai-interaction.sec.yaml file.
 */
export class AiModesTemplateGenerator {
  private readonly aiService: AiIntegrationService;

  constructor(aiService: AiIntegrationService) {
    this.aiService = aiService;
  }

  /**
   * Generates or updates the ai-interaction.sec.yaml file.
   *
   * Merge logic:
   * - Preserves unknown modes and providers
   * - Updates only runs for known providers
   * - Adds new modes if not present
   *
   * @returns Path to generated file
   * @throws Error if workspace root not found or write fails
   */
  async generate(): Promise<string> {
    const root = effectiveWorkspaceRoot();
    if (!root) {
      throw new Error("No workspace root found");
    }

    const lgCfgPath = path.join(root, "lg-cfg");
    const filePath = path.join(lgCfgPath, "ai-interaction.sec.yaml");

    logInfo(`[AiModesTemplateGenerator] Generating ${filePath}`);

    // Ensure lg-cfg directory exists
    if (!fs.existsSync(lgCfgPath)) {
      fs.mkdirSync(lgCfgPath, { recursive: true });
      logDebug("[AiModesTemplateGenerator] Created lg-cfg directory");
    }

    // Collect modes from all providers
    const allModes = this.aiService.getAllSupportedModes();
    logDebug(`[AiModesTemplateGenerator] Collected modes for ${allModes.size} mode types`);

    // Read existing file if present
    let existingContent = "";
    if (fs.existsSync(filePath)) {
      existingContent = fs.readFileSync(filePath, "utf-8");
      logDebug("[AiModesTemplateGenerator] Read existing file");
    }

    // Detect line ending from existing file or OS default
    const eol = this.detectEol(existingContent);

    // Merge and generate new content
    const newContent = this.mergeAndGenerate(existingContent, allModes);

    // Apply platform-appropriate line endings
    const finalContent = eol === "\r\n"
      ? newContent.replace(/\n/g, "\r\n")
      : newContent;

    // Write file
    fs.writeFileSync(filePath, finalContent, "utf-8");
    logInfo(`[AiModesTemplateGenerator] Written ${filePath}`);

    return filePath;
  }

  /**
   * Detects line ending from file content or falls back to OS default.
   */
  private detectEol(content: string): string {
    if (content.includes("\r\n")) return "\r\n";
    if (content.includes("\n")) return "\n";
    return process.platform === "win32" ? "\r\n" : "\n";
  }

  /**
   * Merges existing content with new modes data.
   *
   * Preserves:
   * - Metadata (title, description, tags) for custom modes
   * - Provider order from existing file
   */
  private mergeAndGenerate(
    existingContent: string,
    allModes: Map<string, Map<string, string>>
  ): string {
    // If no existing content, generate fresh
    if (!existingContent.trim()) {
      return this.generateFresh(allModes);
    }

    // Parse existing modes with full metadata and provider order
    const existingModes = this.parseExistingModes(existingContent);

    // Merge: new providers override, unknown providers preserved
    for (const [modeId, newProviders] of allModes) {
      if (!existingModes.has(modeId)) {
        // New mode - create with default metadata
        existingModes.set(modeId, {
          meta: CANONICAL_MODES[modeId] || { title: modeId },
          providerOrder: [],
          runs: new Map()
        });
      }

      const modeData = existingModes.get(modeId);
      if (!modeData) {
        continue;
      }

      // Merge providers, preserving order
      for (const [providerId, runs] of newProviders) {
        // Update runs value
        modeData.runs.set(providerId, runs);

        // Add to order if new provider
        if (!modeData.providerOrder.includes(providerId)) {
          modeData.providerOrder.push(providerId);
        }
      }
    }

    // Regenerate with merged data
    return this.generateFromParsedModes(existingModes);
  }

  /**
   * Parses existing YAML to extract full mode data including metadata and provider order.
   */
  private parseExistingModes(content: string): Map<string, ParsedModeData> {
    const result = new Map<string, ParsedModeData>();

    try {
      const doc = parseDocument(content);
      const root = doc.contents;

      if (!isMap(root)) {
        return result;
      }

      // Navigate: ai-interaction -> mode-sets -> ai-interaction -> modes
      const aiInteraction = root.get("ai-interaction");
      if (!isMap(aiInteraction)) {
        return result;
      }

      const modeSets = aiInteraction.get("mode-sets");
      if (!isMap(modeSets)) {
        return result;
      }

      const aiInteractionModeSet = modeSets.get("ai-interaction");
      if (!isMap(aiInteractionModeSet)) {
        return result;
      }

      const modes = aiInteractionModeSet.get("modes");
      if (!isMap(modes)) {
        return result;
      }

      // Iterate over modes
      for (const pair of modes.items) {
        if (!(pair instanceof Pair)) continue;

        const modeId = String(pair.key);
        const modeNode = pair.value;

        if (!isMap(modeNode)) continue;

        // Extract metadata
        const meta: ModeMeta = {
          title: String(modeNode.get("title") || modeId)
        };

        const description = modeNode.get("description");
        if (description) {
          meta.description = String(description);
        }

        const tagsNode = modeNode.get("tags");
        if (Array.isArray(tagsNode)) {
          meta.tags = tagsNode.map(t => String(t));
        }

        // Extract runs with provider order
        const runsNode = modeNode.get("runs");
        const providerOrder: string[] = [];
        const runs = new Map<string, string>();

        if (isMap(runsNode)) {
          for (const runPair of runsNode.items) {
            if (!(runPair instanceof Pair)) continue;
            const providerId = String(runPair.key);
            const runsValue = String(runPair.value);
            providerOrder.push(providerId);
            runs.set(providerId, runsValue);
          }
        }

        result.set(modeId, { meta, providerOrder, runs });
      }
    } catch (e) {
      logDebug(`[AiModesTemplateGenerator] Failed to parse existing file: ${e}`);
    }

    return result;
  }

  /**
   * Generates fresh YAML content from provider modes (no existing file).
   */
  private generateFresh(allModes: Map<string, Map<string, string>>): string {
    const parsedModes = new Map<string, ParsedModeData>();

    // Process canonical modes first (in order), then any extra modes
    const processedModes = new Set<string>();

    for (const modeId of Object.keys(CANONICAL_MODES)) {
      const providers = allModes.get(modeId);
      if (providers && providers.size > 0) {
        // For new files, sort providers alphabetically for consistent initial output
        const sortedProviderIds = [...providers.keys()].sort();
        parsedModes.set(modeId, {
          meta: CANONICAL_MODES[modeId],
          providerOrder: sortedProviderIds,
          runs: providers
        });
        processedModes.add(modeId);
      }
    }

    // Process any non-canonical modes
    for (const [modeId, providers] of allModes) {
      if (!processedModes.has(modeId) && providers.size > 0) {
        const sortedProviderIds = [...providers.keys()].sort();
        parsedModes.set(modeId, {
          meta: { title: modeId },
          providerOrder: sortedProviderIds,
          runs: providers
        });
      }
    }

    return this.generateFromParsedModes(parsedModes);
  }

  /**
   * Generates YAML content from parsed modes data.
   */
  private generateFromParsedModes(allModes: Map<string, ParsedModeData>): string {
    // Build modes map
    const modesMap = new YAMLMap();

    // Process canonical modes first (in order)
    const processedModes = new Set<string>();
    for (const modeId of Object.keys(CANONICAL_MODES)) {
      const modeData = allModes.get(modeId);
      if (modeData && modeData.runs.size > 0) {
        const modeNode = this.buildModeNode(modeId, modeData);
        modesMap.add(new Pair(modeId, modeNode));
        processedModes.add(modeId);
      }
    }

    // Process any non-canonical modes (preserve their metadata)
    for (const [modeId, modeData] of allModes) {
      if (!processedModes.has(modeId) && modeData.runs.size > 0) {
        const modeNode = this.buildModeNode(modeId, modeData);
        modesMap.add(new Pair(modeId, modeNode));
      }
    }

    // Build ai-interaction mode-set
    const aiInteractionModeSet = new YAMLMap();
    aiInteractionModeSet.add(new Pair("title", "AI Interaction"));
    aiInteractionModeSet.add(new Pair("modes", modesMap));

    // Build mode-sets map
    const modeSetsMap = new YAMLMap();
    modeSetsMap.add(new Pair("ai-interaction", aiInteractionModeSet));

    // Build ai-interaction root
    const aiInteractionRoot = new YAMLMap();
    aiInteractionRoot.add(new Pair("mode-sets", modeSetsMap));

    // Build root map
    const rootMap = new YAMLMap();
    rootMap.add(new Pair("ai-interaction", aiInteractionRoot));

    // Create document
    const doc = new Document(rootMap);
    doc.commentBefore = FILE_HEADER_COMMENT;

    return doc.toString({ indent: 2, lineWidth: 0, singleQuote: true, flowCollectionPadding: false });
  }

  /**
   * Builds a YAML node for a single mode.
   */
  private buildModeNode(modeId: string, modeData: ParsedModeData): YAMLMap {
    const { meta, providerOrder, runs } = modeData;

    // Use canonical metadata for canonical modes, otherwise use parsed/default
    const effectiveMeta = CANONICAL_MODES[modeId] || meta;

    const modeNode = new YAMLMap();

    // Add title
    modeNode.add(new Pair("title", effectiveMeta.title));

    // Add description if present
    if (effectiveMeta.description) {
      modeNode.add(new Pair("description", effectiveMeta.description));
    }

    // Add tags if present (flow style array)
    if (effectiveMeta.tags && effectiveMeta.tags.length > 0) {
      const doc = new Document(effectiveMeta.tags);
      const tagsNode = doc.contents;
      if (tagsNode && tagsNode instanceof YAMLSeq) {
        tagsNode.flow = true;
      }
      modeNode.add(new Pair("tags", tagsNode));
    }

    // Build runs map, preserving provider order
    const runsMap = new YAMLMap();
    for (const providerId of providerOrder) {
      const runsValue = runs.get(providerId);
      if (runsValue !== undefined) {
        runsMap.add(new Pair(providerId, runsValue));
      }
    }
    modeNode.add(new Pair("runs", runsMap));

    return modeNode;
  }
}
