/*
 * AUTO-GENERATED by cli/scripts/gen_models.sh
 * Source: JSON Schemas under cli/lg/*.schema.json
 */

export type Level = "ok" | "warn" | "error";

export interface DiagReport {
  protocol: number;
  tool_version: string;
  root: string;
  config: DiagConfig;
  contexts: string[];
  cache: DiagCache;
  checks: DiagCheck[];
  env: DiagEnv;
}
export interface DiagConfig {
  exists: boolean;
  path: string;
  current?: number | null;
  actual?: number | null;
  fingerprint?: string | null;
  applied?: DiagMigrationRef[];
  last_error?: DiagLastError | null;
  sections?: string[];
  error?: string | null;
}
export interface DiagMigrationRef {
  id: number;
  title: string;
}
export interface DiagLastError {
  message: string;
  traceback?: string | null;
  failed?: DiagMigrationRef | null;
  at?: string | null;
}
export interface DiagCache {
  enabled: boolean;
  path: string;
  exists: boolean;
  sizeBytes: number;
  entries: number;
  rebuilt: boolean;
  error?: string | null;
}
export interface DiagCheck {
  name: string;
  level: Level;
  details?: string | null;
}
export interface DiagEnv {
  python: string;
  platform: string;
  cwd: string;
}
