/*
 * AUTO-GENERATED by cli/scripts/gen_models.sh
 * Source: JSON Schemas under cli/lg/*.schema.json
 */

/**
 * Response schema for 'lg list mode-sets' command
 */
export interface ModeSetsList {
  "mode-sets": ModeSet[];
}
export interface ModeSet {
  /**
   * Unique identifier of the mode set
   */
  id: string;
  /**
   * Human-readable title of the mode set
   */
  title: string;
  modes: Mode[];
}
export interface Mode {
  /**
   * Unique identifier of the mode within the mode set
   */
  id: string;
  /**
   * Human-readable title of the mode
   */
  title: string;
  /**
   * Optional detailed description of the mode
   */
  description?: string;
  /**
   * Array of tags activated by this mode
   */
  tags?: string[];
  /**
   * Additional options specific to this mode
   */
  options?: {
    [k: string]: unknown;
  };
}
