/*
 * AUTO-GENERATED by cli/scripts/gen_models.sh
 * Source: JSON Schemas under cli/lg/*.schema.json
 */

export interface RunResult {
  protocol: number;
  scope: "context" | "section";
  target: string;
  tokenizerLib: string;
  encoder: string;
  ctxLimit: number;
  total: {
    sizeBytes: number;
    tokensProcessed: number;
    tokensRaw: number;
    savedTokens: number;
    savedPct: number;
    ctxShare: number;
    renderedTokens?: number;
    renderedOverheadTokens?: number;
    metaSummary: {
      [k: string]: number;
    };
  };
  files: {
    path: string;
    sizeBytes: number;
    tokensRaw: number;
    tokensProcessed: number;
    savedTokens: number;
    savedPct: number;
    promptShare: number;
    ctxShare: number;
    meta: {
      [k: string]: string | number | boolean;
    };
  }[];
  context?: {
    templateName: string;
    sectionsUsed: {
      [k: string]: number;
    };
    finalRenderedTokens?: number;
    templateOnlyTokens?: number;
    templateOverheadPct?: number;
    finalCtxShare?: number;
  };
}
