/*
 * AUTO-GENERATED by cli/scripts/gen_models.sh
 * Source: JSON Schemas under cli/lg/*.schema.json
 */

/**
 * Response schema for 'list sections' command
 */
export interface SectionsList {
  sections: SectionInfo[];
}
export interface SectionInfo {
  /**
   * Section canonical name
   */
  name: string;
  /**
   * Mode sets after extends resolution (may be empty)
   */
  "mode-sets": ModeSet[];
  /**
   * Tag sets after extends resolution (may be empty)
   */
  "tag-sets": TagSet[];
}
export interface ModeSet {
  /**
   * Unique identifier of the mode set
   */
  id: string;
  /**
   * Human-readable title of the mode set
   */
  title: string;
  modes: Mode[];
  /**
   * True if this mode-set is an integration type (has runs)
   */
  integration?: boolean;
}
export interface Mode {
  /**
   * Unique identifier of the mode within the mode set
   */
  id: string;
  /**
   * Human-readable title of the mode
   */
  title: string;
  /**
   * Optional detailed description of the mode
   */
  description?: string;
  /**
   * Array of tags activated by this mode
   */
  tags?: string[];
  /**
   * Provider-specific run commands mapping provider_id to command string
   */
  runs?: {
    [k: string]: string;
  };
}
export interface TagSet {
  /**
   * Unique identifier of the tag set
   */
  id: string;
  /**
   * Human-readable title of the tag set
   */
  title: string;
  tags: Tag[];
}
export interface Tag {
  /**
   * Unique identifier of the tag within the tag set
   */
  id: string;
  /**
   * Human-readable title of the tag
   */
  title: string;
  /**
   * Optional detailed description of the tag
   */
  description?: string;
}
