/*
 * AUTO-GENERATED by cli/scripts/gen_models.sh
 * Source: JSON Schemas under cli/lg/*.schema.json
 */

/**
 * Response schema for 'lg list tag-sets' command
 */
export interface TagSetsList {
  "tag-sets": TagSet[];
}
export interface TagSet {
  /**
   * Unique identifier of the tag set
   */
  id: string;
  /**
   * Human-readable title of the tag set
   */
  title: string;
  tags: Tag[];
}
export interface Tag {
  /**
   * Unique identifier of the tag within the tag set
   */
  id: string;
  /**
   * Human-readable title of the tag
   */
  title: string;
  /**
   * Optional detailed description of the tag
   */
  description?: string;
}
