/**
 * Base AI Provider
 * 
 * Базовый класс для всех AI-провайдеров с общей функциональностью
 */

import * as vscode from "vscode";
import { logInfo, logDebug, logTrace } from "../../logging/log";
import type { 
  IAiProvider, 
  AiProvider, 
  AiContent, 
  AiProviderOptions, 
  AiProviderInfo,
  ContentType 
} from "./types";

export abstract class BaseAiProvider implements IAiProvider {
  abstract readonly id: AiProvider;
  abstract readonly info: AiProviderInfo;

  /**
   * Проверка доступности провайдера (должна быть реализована в наследниках)
   */
  abstract isAvailable(): Promise<boolean>;

  /**
   * Отправка контента (должна быть реализована в наследниках)
   */
  abstract sendContent(content: AiContent, options?: AiProviderOptions): Promise<void>;

  /**
   * Получение рекомендаций по контенту
   */
  getContentRecommendations(content: AiContent): { warnings: string[]; suggestions: string[] } {
    const warnings: string[] = [];
    const suggestions: string[] = [];
    
    // Общие проверки размера
    const maxRecommended = this.info.capabilities.recommendedMaxLength;
    if (maxRecommended && content.content.length > maxRecommended) {
      warnings.push(`Content length (${this.formatSize(content.content.length)}) exceeds recommended limit (${this.formatSize(maxRecommended)})`);
      suggestions.push('Consider breaking down the content into smaller parts');
    }
    
    // Проверки по типу контента
    if (content.type === 'context' && content.metadata.fileCount && content.metadata.fileCount > 50) {
      warnings.push(`Context includes ${content.metadata.fileCount} files, which might be too many for effective processing`);
      suggestions.push('Consider using more specific filters to reduce the number of files');
    }
    
    if (content.type === 'listing' && content.content.length > 100000) {
      suggestions.push('Large listings work better when focused on specific modules or components');
    }
    
    return { warnings, suggestions };
  }

  /**
   * Создание префикса для контента
   */
  protected createContentPrefix(content: AiContent): string {
    const { type, metadata } = content;
    const icon = this.getContentTypeIcon(type);
    
    switch (type) {
      case 'context':
        return `# ${icon} LG Context: ${metadata.name}\n\n` +
               `Generated by Listing Generator from template \`${metadata.name}\`.\n` +
               `This context was carefully prepared to fit within model limits.\n` +
               `Size: ${this.formatSize(metadata.size)}${metadata.fileCount ? `, Files: ${metadata.fileCount}` : ''}`;
               
      case 'listing':
        const mode = metadata.mode || 'all';
        return `# ${icon} LG Listing: ${metadata.name} (${mode})\n\n` +
               `Generated by Listing Generator from section \`${metadata.name}\` in \`${mode}\` mode.\n` +
               `This listing includes only relevant files that passed the configured filters.\n` +
               `Size: ${this.formatSize(metadata.size)}${metadata.fileCount ? `, Files: ${metadata.fileCount}` : ''}`;
               
      case 'generic':
      default:
        return `# ${icon} LG Content: ${metadata.name}\n\n` +
               `Generated by Listing Generator.\n` +
               `Size: ${this.formatSize(metadata.size)}`;
    }
  }

  /**
   * Получение иконки для типа контента
   */
  private getContentTypeIcon(type: ContentType): string {
    switch (type) {
      case 'context': return '🎯';
      case 'listing': return '📋';
      case 'generic': return '📄';
      default: return '📄';
    }
  }

  /**
   * Форматирование размера
   */
  protected formatSize(length: number): string {
    if (length < 1000) {
      return `${length} chars`;
    } else if (length < 1000000) {
      return `${(length / 1000).toFixed(1)}K chars`;
    } else {
      return `${(length / 1000000).toFixed(1)}M chars`;
    }
  }

  /**
   * Получение опций из конфигурации VS Code
   */
  protected getConfigOptions(): AiProviderOptions {
    const cfg = vscode.workspace.getConfiguration();
    
    return {
      addPrefix: cfg.get<boolean>("lg.ai.addPrefix", false),
      showDetailedNotifications: cfg.get<boolean>("lg.ai.showDetailedNotifications", false),
      autoOpenPanel: cfg.get<boolean>("lg.ai.autoOpenPanel", true),
      maxContentLength: cfg.get<number>("lg.ai.maxContentLength", 1000000),
    };
  }

  /**
   * Объединение опций (переданные перезаписывают конфигурационные)
   */
  protected mergeOptions(configOptions: AiProviderOptions, passedOptions?: AiProviderOptions): AiProviderOptions {
    return {
      ...configOptions,
      ...(passedOptions || {})
    };
  }

  /**
   * Копирование контента в буфер обмена
   */
  protected async copyToClipboard(finalContent: string): Promise<void> {
    await vscode.env.clipboard.writeText(finalContent);
    logInfo(`[${this.id}] Content copied to clipboard, length: ${finalContent.length} chars`);
    logDebug(`[${this.id}] Content preview: ${finalContent.slice(0, 200)}...`);
  }

  /**
   * Показ уведомления пользователю
   */
  protected async showNotification(content: AiContent, options: AiProviderOptions, success: boolean = true): Promise<void> {
    const size = this.formatSize(content.content.length);
    
    if (options.showDetailedNotifications) {
      const instructions = this.getDetailedInstructions();
      const message = success 
        ? `✅ LG content copied to clipboard (${size})\n\n📋 Next steps:\n${instructions}`
        : `❌ Failed to send content to AI`;
        
      await vscode.window.showInformationMessage(
        message,
        { modal: false },
        "📚 Got it"
      );
    } else {
      const message = success
        ? `📋 Content copied to clipboard (${size})`
        : `❌ Failed to send to ${this.info.name}`;
        
      if (success) {
        vscode.window.showInformationMessage(message);
      } else {
        vscode.window.showErrorMessage(message);
      }
    }
  }

  /**
   * Получение детальных инструкций для пользователя
   */
  protected abstract getDetailedInstructions(): string;

  /**
   * Попытка автоматического открытия AI панели
   */
  protected abstract tryAutoOpenPanel(): Promise<boolean>;


}
